/**
 * @file    version.h
 * @brief   Software version header (auto-generated)
 * @note    This file is auto-generated by tasks.py
 *          Do not edit manually
 */

#ifndef __VERSION_H__
#define __VERSION_H__

/* Software version based on git hash */
#define SOFTWARE_VERSION (0xb44fbf6)

/* Git hash as string */
#define SOFTWARE_VERSION_STRING "b44fbf6"

#endif /* __VERSION_H__ */
